name: Build and Release ZygorGuideLoader

on:
  push:
    tags:
      - "v*" # Trigger only when you push a tag starting with 'v' (e.g., v1.0)

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write # Crucial for creating a Release

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install customtkinter pyinstaller

      - name: Build Executable with PyInstaller
        run: |
          pyinstaller --noconsole --onefile --collect-all customtkinter --icon=favicon.ico main.py

      - name: Rename Executable
        run: rename dist\main.exe ZygorGuideLoader.exe

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/ZygorGuideLoader.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
